spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/login_system?allowPublicKeyRetrieval=true&useSSL=false
    password: Erdemerdem.01
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
